### ISSUE TITLE
ParseError: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by ChZhg123** [shopwwi/webman-socialite#2]
ParseError: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in D:\phpstudy_pro\WWW\webman\vendor\shopwwi\webman-socialite\src\SocialiteManager.php:25
Stack trace:
#0 D:\phpstudy_pro\WWW\webman\vendor\composer\ClassLoader.php(346): Composer\Autoload\includeFile('D:\\phpstudy_pro...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Shopwwi\\WebmanS...')
#2 D:\phpstudy_pro\WWW\webman\vendor\shopwwi\webman-socialite\src\Facade\Socialite.php(48): spl_autoload_call('Shopwwi\\WebmanS...')
#3 D:\phpstudy_pro\WWW\webman\vendor\shopwwi\webman-socialite\src\Facade\Socialite.php(60): Shopwwi\WebmanSocialite\Facade\Socialite::instance()
#4 D:\phpstudy_pro\WWW\webman\app\index\controller\AuthController.php(35): Shopwwi\WebmanSocialite\Facade\Socialite::__callStatic('driver', Array)
#5 D:\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\App.php(319): app\index\controller\AuthController->fastLogin(Object(support\Request))
#6 D:\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\App.php(349): Webman\App::Webman\{closure}(Object(support\Request))
#7 D:\phpstudy_pro\WWW\webman\app\middleware\RecordVisit.php(36): Webman\App::Webman\{closure}(Object(support\Request))
#8 D:\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\App.php(341): app\middleware\RecordVisit->process(Object(support\Request), Object(Closure))
#9 D:\phpstudy_pro\WWW\webman\vendor\webman\log\src\Middleware.php(58): Webman\App::Webman\{closure}(Object(support\Request))
#10 D:\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\App.php(341): Webman\Log\Middleware->process(Object(support\Request), Object(Closure))
#11 D:\phpstudy_pro\WWW\webman\app\middleware\CrossRequest.php(19): Webman\App::Webman\{closure}(Object(support\Request))
#12 D:\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\App.php(341): app\middleware\CrossRequest->process(Object(support\Request), Object(Closure))
#13 D:\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\App.php(560): Webman\App::Webman\{closure}(Object(support\Request))
#14 D:\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\App.php(148): Webman\App::findRoute(Object(Workerman\Connection\TcpConnection), '/index/fastLogi...', 'GET/index/fastL...', Object(support\Request))
#15 D:\phpstudy_pro\WWW\webman\vendor\workerman\workerman\Connection\TcpConnection.php(646): Webman\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(support\Request))
#16 D:\phpstudy_pro\WWW\webman\vendor\workerman\workerman\Events\Select.php(311): Workerman\Connection\TcpConnection->baseRead(Resource id #252)
#17 D:\phpstudy_pro\WWW\webman\vendor\workerman\workerman\Worker.php(1479): Workerman\Events\Select->loop()
#18 D:\phpstudy_pro\WWW\webman\vendor\workerman\workerman\Worker.php(1399): Workerman\Worker::forkWorkersForWindows()
#19 D:\phpstudy_pro\WWW\webman\vendor\workerman\workerman\Worker.php(560): Workerman\Worker::forkWorkers()
#20 D:\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\support\App.php(131): Workerman\Worker::runAll()
#21 D:\phpstudy_pro\WWW\webman\start.php(4): support\App::run()
#22 {main}

**Comment by ChZhg123** [comment]
调用  Socialite::driver('qq')->redirect()报错
